set_schedule_slot:
  description: Set schedule slot for specific day and hour
  fields:
    day:
      description: Day of week (0=Monday, 6=Sunday)
      example: 0
      required: true
    hour:
      description: Hour (0-23)
      example: 7
      required: true
    target_temp:
      description: Target temperature in celsius
      example: 21.5
      required: true
    room:
      description: Room name (optional)
      example: "living_room"
      default: "default"

set_learning_mode:
  description: Switch between learning and operating mode
  fields:
    mode:
      description: Learning mode (true) or operating mode (false)
      example: true
      required: true

trigger_training:
  description: Manually trigger model training

clear_training_data:
  description: Clear all collected training data
